### ISSUE TITLE
Error in ggtitle

### ISSUE THREAD

**Issue by SamWell16** [xgaoo/ClusterMap#16]
There is a similar error already reported by lc822, but no one responded to it. Since I am struggling with it too, I thought to post mine here as well. 

Following the tutorial, when I run code below;
 
res <- cluster_map(marker_file_list, edge_cutoff = 0.1, output = 'SLFvsDLF', single_obj_list = single_obj_list, comb_obj = objList$BAL)

I get this ggtitle error right away.
match sub-clusters
circos plot
recolor SLF
[1] "Using Seurat v3"
[1] "Using Seurat v3"
Saving 7 x 7 in image
Error in ggtitle(paste(toupper(output))) + ggsave(paste0(output, ".recolor.tsne.png")) : 
  non-numeric argument to binary operator

Any help with that would be very much appreciated!

**Comment by jmrussell** [comment]
This should be fixed now, please reinstall ClusterMap and try again with your data and let me know if you run into the error again.

**Comment by SamWell16** [comment]
It worked just fine. Thanks for fixing it.
