### ISSUE TITLE
Problem with installing ClusterMap

### ISSUE THREAD

**Issue by fereshtehizadi** [xgaoo/ClusterMap#3]
Hi,

Sorry,

Whatever I am trying to install ClusterMap, I am getting this error

```
> library('devtools')  
> 
> install_github('ClusterMap','xgaoo')  
Error in parse_repo_spec(repo) : 
  Invalid git repo specification: 'ClusterMap'
> 
> 
```

Could you please help me in installing this software?

Thanks a lot in advance

**Comment by xgaoo** [comment]
Hi,
ClusterMap was build under R-3.4.3. It is not updated to R-3.5 yet.

**Comment by xbjie123** [comment]
Hi, 
In fact, I used R-3.4.3. When installing, it's still the same error.

`> install_github('ClusterMap','xgaoo') 
Error in parse_repo_spec(repo) : 
  Invalid git repo specification: 'ClusterMap'`

Could you know what's the problem?

Best
Thanks
BJ

**Comment by Gorman222** [comment]
Hi xbjie,

Try:
devtools::install_github("xgaoo/ClusterMap")

**Comment by J-Street015** [comment]
Hi, 
I tried installing ClusterMap under R-3.4.3, however get the following message: 
Skipping 1 packages not available: mvtnorm

Checking for mvtnorm https://cran.r-project.org/web/packages/mvtnorm/index.html, I find that this package depends on  R (≥ 3.5.0). Is there any chance to get the ClusterMap package installed anyway, or will it be updated for R-3.5.1 ?
Thanks for your help!
JS

**Comment by xgaoo** [comment]
Hi JS,
I have no problem installing mvtnorm under R-3.4.3.

> R.Version()$version.string
[1] "R version 3.4.3 (2017-11-30)"
> library(mvtnorm)
>

**Comment by xgaoo** [comment]
> Hi,
> In fact, I used R-3.4.3. When installing, it's still the same error.
> 
> `> install_github('ClusterMap','xgaoo') Error in parse_repo_spec(repo) : Invalid git repo specification: 'ClusterMap'`
> 
> Could you know what's the problem?
> 
> Best
> Thanks
> BJ

Hi xbjie,
Sorry for the late reply. Is your Seurat version >=2.2.1?

**Comment by Gorman222** [comment]
The install instructions are incorrect.
Try
`install_github("xgaoo/ClusterMap")`

**Comment by samadelk** [comment]
I had this issue and i could install the package using: 
install_github("xgaoo/ClusterMap")

**Comment by gabrielascui** [comment]
I was able to install ClusterMap in R 3.6.1 after running:

`BiocManager::install("multtest")`

And then:

`install_github("xgaoo/ClusterMap)`

Using Seurat 3.1.1
