### ISSUE TITLE
Error in parse with installing ClusterMap

### ISSUE THREAD

**Issue by gxg2002cn** [xgaoo/ClusterMap#4]
Hi Gao Xin,
I met a error in parse message when installing ClusterMap as below. I tried R-3.4.3 and R-3.5.1 but all the same error. Could you help me to figure out how to fix the problem. Thanks a lot!
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
> install_github("xgaoo/ClusterMap")
Downloading GitHub repo xgaoo/ClusterMap@master
√  checking for file 'C:\Users\181\AppData\Local\Temp\RtmpyS43wn\remotes1d684c717625\xgaoo-ClusterMap-7d0e21c/DESCRIPTION' ...
-  preparing 'ClusterMap':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'ClusterMap_0.1.0.tar.gz'
   
Installing package into ‘C:/Users/181/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'ClusterMap' ...
** R
Error in parse(outFile) : 
  C:/Users/181/AppData/Local/Temp/Rtmpe4R6IY/R.INSTALL3cd0279f77d/ClusterMap/R/cluster_map.R:46:92: unexpected ')'
45:         ## save heatmap png
46:         png(paste0(output, '.heatmap.hcluster.png'), height = 480*length(marker_file_list)))
                                                                                               ^
ERROR: unable to collate and parse R files for package 'ClusterMap'
* removing 'C:/Users/181/Documents/R/win-library/3.5/ClusterMap'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/181/AppData/Local/Temp/RtmpyS43wn/file1d685f6b31e6/ClusterMap_0.1.0.tar.gz’ had non-zero exit status

**Comment by xgaoo** [comment]
Hi, 
There was a typo when I tried to adjust the figure size. Sorry. It is fixed now. Please try again. Please use R-3.4.3, it is not tested under the newest version of R yet.


thanks,
Xin 
 
 
------------------ Original ------------------

**Comment by gxg2002cn** [comment]
Hi Xin,
Thank you very much for your help! I started!
Best,
Xiaogang

**Comment by xbjie123** [comment]
Hi Xin,
Still the similar error. I used R-3.4.3.
How to deal with this?
![default](https://user-images.githubusercontent.com/35304822/50783340-7cac7b00-12e5-11e9-8ed8-fde1a490f276.PNG)

Thank you very much~~
Best
BJ

**Comment by xgaoo** [comment]
Hi BJ,
Thank you for pointing this out. I fixed it. Please try again. Sorry for the inconvenient.
best,
Xin

**Comment by xbjie123** [comment]
It works now.
Thank you for everything.
Best
BJ

**Comment by xbjie123** [comment]
Hi Xin,

Did you published this methods? Where could I find the manuscript?

BJ

**Comment by xgaoo** [comment]
Hi BJ,
The paper is just accepted. It will be online in several days. There is an old version on BioRxiv https://www.biorxiv.org/content/early/2018/06/29/331330


Thanks,
Xin
 
 
------------------ Original ------------------

**Comment by xbjie123** [comment]
Get it.

Thank you very much.
