### ISSUE TITLE
Using Seurat v3

### ISSUE THREAD

**Issue by jdime** [xgaoo/ClusterMap#6]
Hello,

This isn't really an issue, but more a request. Have you guys thought about updating ClusterMap to run using Seurat v3 commands? For example, in Seurat v3 the `obj@ident` called by `cluster_map()` is called `Idents(object = object)`
https://satijalab.org/seurat/essential_commands.html
Thanks.

**Comment by xgaoo** [comment]
Thank you for using ClusterMap. We will work on the updating, but it may take a while. Sorry for the inconvenience.

--------------原始邮件--------------
发件人："Javier Diaz-Mejia "<notifications@github.com>;
发送时间：2019年5月29日(星期三) 凌晨4:43
收件人："xgaoo/ClusterMap" <ClusterMap@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[xgaoo/ClusterMap] Seruat v3 (#6)
-----------------------------------

 
Hello,
 
This isn't really an issue, but more a request. Have you guys thought about updating ClusterMap to run using Seurat v3 commands? For example, in Seurat v3 the obj@ident called by cluster_map() is called Idents(object = object)
 https://satijalab.org/seurat/essential_commands.html
 Thanks.
