### ISSUE TITLE
  no slot of name "ident" for this object of class "Seurat

### ISSUE THREAD

**Issue by weiliuyuan** [xgaoo/ClusterMap#7]
Hi, 

I am trying to use clusterMap, but getting the error of the slot name of Seurat object. 
The code i used: 
`res <- cluster_map(marker_file_list, edge_cutoff = 0.1, output="test", single_obj_list = single_obj_list, comb_obj = objList$combine)`
The output: 
**_match sub-clusters
Error in summary(obj@ident) : 
  no slot of name "ident" for this object of class "Seurat"_**

I was using Seurat3. Should i switch to Seurat2? Could you please let me know which version of Seurat that ClusterMap used? 

Many thanks!

**Comment by xgaoo** [comment]
Hi Wei,
ClusterMap is using Seurat2. It will take us a while to update it to Seurat3. Thank you for trying ClusterMap.
best,
Xin

--------------原始邮件--------------
发件人："Wei Liu "<notifications@github.com>;
发送时间：2019年6月17日(星期一) 晚上10:03
收件人："xgaoo/ClusterMap" <ClusterMap@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[xgaoo/ClusterMap]   no slot of name "ident" for this object of class "Seurat (#7)
-----------------------------------

 
Hi,
 
I am trying to use clusterMap, but getting the error of the slot name of Seurat object.
 The code i used:
 res <- cluster_map(marker_file_list, edge_cutoff = 0.1, output="test", single_obj_list = single_obj_list, comb_obj = objList$combine)
 The output:
 match sub-clusters
 Error in summary(obj@ident) :
 no slot of name "ident" for this object of class "Seurat"
 
I was using Seurat3. Should i switch to Seurat2? Could you please let me know which version of Seurat that ClusterMap used?
 
Many thanks!

**Comment by gabrielascui** [comment]
Same problem here, is there a way to use obj@orig.ident instead of obj@ident ?

**Comment by xgaoo** [comment]
We are working on the updated version using Seurat v3 and it will be released soon.
Thank you!
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by stets43** [comment]
Any time table on when the updated version will be released? I am also experiencing this error.

Thanks!

**Comment by jmrussell** [comment]
Hi @stets43, I have updated ClusterMap to work with version 3 of Seurat. Please let me know if you run into any issues.

**Comment by stets43** [comment]
Works great, Thanks! Loving the circos plot.
